#!/usr/bin/env bash
exec bundle exec /var/www/service_portal/bin/rails server -b 'ssl://0.0.0.0:5000?key=/var/www/service_portal/config/ssl/localhost.key&cert=/var/www/service_portal/config/ssl/localhost.crt'

