=begin
Insights Service Catalog API

This is a API to fetch and order catalog items from different cloud sources

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  # Portfolio Routes
  add_swagger_route 'POST', '/r/insights/platform/service-catalog/1.0.0/portfolios', controller_name: 'admins', action_name: 'add_portfolio'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolios', controller_name: 'users', action_name: 'list_portfolios'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolios/{portfolio_id}', controller_name: 'admins', action_name: 'fetch_portfolio_with_id'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolios/{portfolio_id}', controller_name: 'users', action_name: 'fetch_portfolio_with_id'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolios', controller_name: 'admins', action_name: 'list_portfolios'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolios/{portfolio_id}/portfolio_items', controller_name: 'admins', action_name: 'fetch_portfolio_items_with_portfolio'
  add_swagger_route 'POST', '/r/insights/platform/service-catalog/1.0.0/portfolios/{portfolio_id}/portfolio_items/{portfolio_item_id}', controller_name: 'admins', action_name: 'add_portfolio_item_to_portfolio'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolios/{portfolio_id}/portfolio_items/{portfolio_item_id}', controller_name: 'admins', action_name: 'fetch_portfolio_item_from_portfolio'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolios/{portfolio_id}/portfolio_items/{portfolio_item_id}', controller_name: 'users', action_name: 'fetch_portfolio_item_from_portfolio'
  add_swagger_route 'POST', '/r/insights/platform/service-catalog/1.0.0/portfolio_items', controller_name: 'admins', action_name: 'add_portfolio_item'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolio_items', controller_name: 'admins', action_name: 'list_portfolio_items'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/portfolio_items', controller_name: 'users', action_name: 'list_portfolio_items'

  # Catalog / Provider Routes
  add_swagger_route 'POST', '/r/insights/platform/service-catalog/1.0.0/providers', controller_name: 'users', action_name: 'add_provider'
  add_swagger_route 'POST', '/r/insights/platform/service-catalog/1.0.0/orders/{order_id}/items', controller_name: 'users', action_name: 'add_to_order'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/catalog_items', controller_name: 'users', action_name: 'catalog_items'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/providers/{provider_id}/catalog_items/{catalog_id}/plans/{plan_id}/parameters', controller_name: 'users', action_name: 'catalog_plan_parameters'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/providers/{provider_id}/catalog_items/{catalog_id}/plans/{plan_id}/json_schema', controller_name: 'users', action_name: 'catalog_plan_schema'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/providers/{provider_id}/catalog_items', controller_name: 'users', action_name: 'fetch_catalog_item_with_provider'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/providers/{provider_id}/catalog_items/{catalog_id}', controller_name: 'users', action_name: 'fetch_catalog_item_with_provider_and_catalog_id'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/providers/{provider_id}/catalog_items/{catalog_id}/plans', controller_name: 'users', action_name: 'fetch_plans_with_provider_and_catalog_id'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/orders/{order_id}/items/{order_item_id}', controller_name: 'users', action_name: 'list_order_item'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/orders/{order_id}/items', controller_name: 'users', action_name: 'list_order_items'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/orders', controller_name: 'users', action_name: 'list_orders'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/order_items/{order_item_id}/progress_messages', controller_name: 'users', action_name: 'list_progress_messages'
  add_swagger_route 'GET', '/r/insights/platform/service-catalog/1.0.0/providers', controller_name: 'users', action_name: 'list_providers'
  add_swagger_route 'POST', '/r/insights/platform/service-catalog/1.0.0/orders', controller_name: 'users', action_name: 'new_order'
  add_swagger_route 'POST', '/r/insights/platform/service-catalog/1.0.0/orders/{order_id}', controller_name: 'users', action_name: 'submit_order'
end
