=begin
Insights Service Catalog API

This is a API to fetch and order catalog items from different cloud sources

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class AdminsController < ApplicationController

  def add_portfolio
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def list_portfolios
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
