=begin
Insights Service Catalog API

This is a API to fetch and order catalog items from different cloud sources

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UsersController < ApplicationController

  def add_provider
    object = Provider.create(:name       => params[:name],
                             :url        => params[:url],
                             :token      => params[:token],
                             :user       => params[:user],
                             :password   => params[:password],
                             :verify_ssl => params.fetch(:verify_ssl, true))
    render json: object.to_hash
  end

  def add_to_order
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def catalog_items
    result = Provider.all.collect { |prov| prov.fetch_catalog_items }.flatten
    render json: result
  end

  def catalog_plan_parameters
    prov = Provider.where(:id => params['provider_id']).first
    result = prov.fetch_catalog_plan_parameters(params['catalog_id'], params['plan_id']) if prov
    render json: result
  end

  def fetch_catalog_item_with_provider
    prov = Provider.where(:id => params['provider_id']).first
    result = prov.fetch_catalog_items(params['catalog_id']) if prov
    render json: result
  end

  def fetch_catalog_item_with_provider_and_catalog_id
    fetch_catalog_item_with_provider
  end

  def fetch_plans_with_provider_and_catalog_id
    prov = Provider.where(:id => params['provider_id']).first
    result = prov.fetch_catalog_plans(params['catalog_id']) if prov
    render json: result
  end

  def list_order_item
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def list_order_items
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def list_orders
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def list_portfolios
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def list_progress_messages
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def list_providers
    render json: Provider.all.collect(&:to_hash)
  end

  def new_order
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def submit_order
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
