=begin
Insights Service Catalog API

This is a API to fetch and order catalog items from different cloud sources

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Order < ApplicationRecord
  acts_as_tenant(:tenant)

  has_many :order_items

  after_initialize :set_defaults, unless: :persisted?
  NON_DATE_ATTRIBUTES = %w(state)
  DATE_ATTRIBUTES     = %w(created_at ordered_at completed_at)

  def as_json(_options = {})
    attributes.slice(*NON_DATE_ATTRIBUTES).tap do |hash|
      DATE_ATTRIBUTES.each do |attr|
        hash[attr] = self.send(attr.to_sym).iso8601 if self.send(attr.to_sym)
      end
    end.merge(:id => id.to_s)
  end

  def set_defaults
    self.state = "Created"
  end

  def finalize_order
    item_states = order_items.collect(&:state)
    if item_states.include?('Failed')
      self.state = "Failed"
    elsif item_states.include?('Completed') && item_states.count == order_items.count
      self.state = 'Completed'
    else
      self.state = 'Ordered'
    end
    save!
  end
end
