=begin
Insights Service Catalog API

This is a API to fetch and order catalog items from different cloud sources

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class PortfolioItem < ApplicationRecord
  acts_as_tenant(:tenant)

  attr_accessor :portfolio_id
  has_and_belongs_to_many :portfolios

  validates :service_offering_ref, :presence => true

  SERVICE_OFFERING_KEY = 'service_offering_ref'.freeze

  def self.create!(params)
    sanitized = sanitize_params(params)
    service_offering = ServiceOffering.find(sanitized[SERVICE_OFFERING_KEY])
    super(service_offering.to_normalized_params)
  end

  def self.create(params)
    sanitized = sanitize_params(params)
    service_offering = ServiceOffering.find(sanitized[SERVICE_OFFERING_KEY])
    super(service_offering.to_normalized_params)
  end

  def self.sanitize_params(params)
    HashWithIndifferentAccess.new(params)
  end
end
