=begin
Insights Service Catalog API

This is a API to fetch and order catalog items from different cloud sources

OpenAPI spec version: 1.0.0
Contact: you@your-company.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class ProgressMessage < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?
  NON_DATE_ATTRIBUTES = %w(level message)
  DATE_ATTRIBUTES     = %w(received_at)

  def to_hash
    attributes.slice(*NON_DATE_ATTRIBUTES).tap do |hash|
      DATE_ATTRIBUTES.each do |attr| 
        hash[attr] = self.send(attr.to_sym).iso8601 if self.send(attr.to_sym)
      end
    end.merge(:id => id.to_s)
  end

  def set_defaults
    self.received_at = DateTime.now
  end
end
